backend:
  name: github
  repo: TwoStoryRobot/knit2yarns.github.io
  branch: master

media_folder: "/img/uploads"

collections:
  - name: "classes"
    label: "Classes"
    folder: "_classes"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image_url", widget: "image", required: false }
      - { label: "Meta 1", name: "meta_1", widget: "string" }
      - { label: "Meta 2", name: "meta_2", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Price Details", name: "price_details", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text" }
